version: '3.1'

services:

  # SSL対応
  https-portal:
    image: steveltn/https-portal:1
    container_name: web_https-portal
    ports:
      - 80:80
      - 443:443
    depends_on:
      - nginx
    restart: always
    volumes:
      - ./dockerfiles/certs:/var/lib/https-portal
    environment:
      STAGE: 'production'
      DOMAINS: >-
        chikaukume.tk -> http://nginx
      WORKER_PROCESSES: auto
      WORKER_CONNECTIONS: 2048
      CLIENT_MAX_BODY_SIZE: '128M'

  # Nginx
  nginx:
    image: nginx:stable
    container_name: web_nginx
    volumes:
      - ./dockerfiles/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./dockerfiles/nginx/conf.d:/etc/nginx/conf.d
      - ./dockerfiles/nginx/log:/var/log/nginx
      - ./dockerfiles/nginx/www:/var/www
    depends_on:
      - wordpress
    restart: always

  wordpress:
    container_name: wp-homepage
    build: 
      context: .
      dockerfile: ./dockerfiles/wordpress/Dockerfile
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ./:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    container_name: db-homepage
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: