version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: always
    container_name: wp-baseAppLabo
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: chikau
      WORDPRESS_DB_PASSWORD: ChikauKume0730
      WORDPRESS_DB_NAME: baseAppLabo
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    container_name: db-baseAppLabo
    environment:
      MYSQL_DATABASE: baseAppLabo
      MYSQL_USER: chikau
      MYSQL_PASSWORD: ChikauKume0730
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: