version: '3.1'

services:

  wordpress:
    container_name: wp-homepage
    build: 
      context: .
      dockerfile: ./dockerfiles/wordpress/Dockerfile
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: chikau
      WORDPRESS_DB_PASSWORD: ChikauKume0730
      WORDPRESS_DB_NAME: homepage
    volumes:
      - ./:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    container_name: db-homepage
    environment:
      MYSQL_DATABASE: homepage
      MYSQL_USER: chikau
      MYSQL_PASSWORD: ChikauKume0730
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db: